package com.streambridge.transform;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.streambridge.transform.proto.TransformRequest;
import com.streambridge.transform.proto.TransformResponse;
import com.streambridge.transform.proto.TransformServiceGrpc;
import io.grpc.Status;
import io.grpc.stub.StreamObserver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * TransformServiceImpl — the actual gRPC server logic.
 *
 * JAVA CONCEPT: Extending a generated base class
 * ──────────────────────────────────────────────
 * TransformServiceGrpc.TransformServiceImplBase is auto-generated from transform.proto.
 * It defines abstract methods for each RPC. We override them here.
 * Python equivalent: implementing an abstract base class generated by grpc_tools.protoc.
 *
 * WHAT IS StreamObserver?
 * ───────────────────────
 * StreamObserver<T> is gRPC Java's callback interface for sending responses.
 * Instead of returning a value, you call:
 *   responseObserver.onNext(value)     — send one response
 *   responseObserver.onCompleted()     — signal no more responses
 *   responseObserver.onError(throwable) — signal failure
 *
 * For unary RPCs: exactly one onNext() then onCompleted().
 * For server-streaming: many onNext() calls then one onCompleted().
 *
 * Python gRPC equivalent:
 *   Unary:           return value directly from servicer method
 *   Server-streaming: yield values from a generator method
 */
public class TransformServiceImpl extends TransformServiceGrpc.TransformServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(TransformServiceImpl.class);

    // ObjectMapper is thread-safe after configuration — safe to share as a static field.
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final TypeReference<Map<String, Object>> MAP_TYPE = new TypeReference<>() {};

    // PII field names to redact. These are the snake_case forms — camelCase
    // conversion runs BEFORE PII redaction, so "creditCard" becomes "credit_card"
    // before we check against this set.
    private static final Set<String> PII_FIELDS = Set.of("email", "phone", "credit_card", "ssn");

    // Regex: insert underscore between a lowercase letter and an uppercase letter.
    // "userId" → matches "r" + "I" → inserts "_" → "user_Id" → toLowerCase → "user_id"
    private static final Pattern CAMEL_TO_SNAKE = Pattern.compile("([a-z])([A-Z])");

    // ── Unary RPC ─────────────────────────────────────────────────────────────

    /**
     * Transform: applies all 4 steps in sequence, returns a single response.
     *
     * UNARY RPC PATTERN:
     *   1. Validate input → onError() if invalid
     *   2. Do work
     *   3. onNext(result) → onCompleted()
     *
     * gRPC Status codes are like HTTP status codes but for RPC.
     * INVALID_ARGUMENT = 400 Bad Request equivalent.
     * INTERNAL         = 500 Internal Server Error equivalent.
     */
    @Override
    public void transform(TransformRequest request,
                          StreamObserver<TransformResponse> responseObserver) {
        if (request.getEventId().isBlank()) {
            responseObserver.onError(
                Status.INVALID_ARGUMENT
                    .withDescription("event_id cannot be blank")
                    .asRuntimeException()
            );
            return;
        }

        log.debug("transform() called for event_id={}", request.getEventId());

        try {
            Map<String, Object> payload = MAPPER.readValue(request.getRawJson(), MAP_TYPE);

            payload = convertCamelToSnake(payload);
            payload = removeNullsAndEmpty(payload);
            payload = coerceNumericStrings(payload);
            payload = redactPiiFields(payload);

            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(request.getEventId())
                .setTransformedJson(MAPPER.writeValueAsString(payload))
                .setSuccess(true)
                .addTransformationNotes("camelCase→snake_case, nulls removed, numbers coerced, PII redacted")
                .build());
            responseObserver.onCompleted();

        } catch (Exception e) {
            log.error("transform() failed for event_id={}: {}", request.getEventId(), e.getMessage());
            // Return a response rather than onError so the client can inspect the message.
            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(request.getEventId())
                .setSuccess(false)
                .setErrorMessage(e.getMessage())
                .build());
            responseObserver.onCompleted();
        }
    }

    // ── Server-streaming RPC ──────────────────────────────────────────────────

    /**
     * StreamTransform: streams one TransformResponse after each transformation step.
     *
     * SERVER-STREAMING PATTERN:
     *   onNext() × N  →  onCompleted()
     *
     * This lets the caller observe each step as it finishes — useful for
     * audit trails and debugging. In Python gRPC this would be a generator:
     *
     *   def StreamTransform(self, request, context):
     *       payload = json.loads(request.raw_json)
     *       payload = convert_camel_to_snake(payload)
     *       yield TransformResponse(transformed_json=json.dumps(payload), ...)
     *       payload = remove_nulls(payload)
     *       yield TransformResponse(...)
     *       ...
     *
     * WHY HTTP/2 MAKES THIS EFFICIENT:
     * Each onNext() call sends a frame on an already-open HTTP/2 stream —
     * no new TCP handshake per step. Over REST you'd need 4 separate HTTP calls.
     */
    @Override
    public void streamTransform(TransformRequest request,
                                StreamObserver<TransformResponse> responseObserver) {
        if (request.getEventId().isBlank()) {
            responseObserver.onError(
                Status.INVALID_ARGUMENT
                    .withDescription("event_id cannot be blank")
                    .asRuntimeException()
            );
            return;
        }

        log.debug("streamTransform() called for event_id={}", request.getEventId());
        String id = request.getEventId();

        try {
            Map<String, Object> payload = MAPPER.readValue(request.getRawJson(), MAP_TYPE);

            // Step 1: camelCase → snake_case
            payload = convertCamelToSnake(payload);
            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(id)
                .setTransformedJson(MAPPER.writeValueAsString(payload))
                .setSuccess(true)
                .addTransformationNotes("Step 1: Converted camelCase keys to snake_case")
                .build());

            // Step 2: remove null/empty fields
            payload = removeNullsAndEmpty(payload);
            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(id)
                .setTransformedJson(MAPPER.writeValueAsString(payload))
                .setSuccess(true)
                .addTransformationNotes("Step 2: Removed null and empty fields")
                .build());

            // Step 3: coerce numeric strings
            payload = coerceNumericStrings(payload);
            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(id)
                .setTransformedJson(MAPPER.writeValueAsString(payload))
                .setSuccess(true)
                .addTransformationNotes("Step 3: Coerced numeric strings to numbers")
                .build());

            // Step 4: redact PII fields
            payload = redactPiiFields(payload);
            responseObserver.onNext(TransformResponse.newBuilder()
                .setEventId(id)
                .setTransformedJson(MAPPER.writeValueAsString(payload))
                .setSuccess(true)
                .addTransformationNotes("Step 4: Redacted PII fields (email, phone, credit_card, ssn)")
                .build());

            responseObserver.onCompleted();

        } catch (Exception e) {
            log.error("streamTransform() failed for event_id={}: {}", id, e.getMessage());
            responseObserver.onError(
                Status.INTERNAL.withDescription(e.getMessage()).asRuntimeException()
            );
        }
    }

    // ── Transformation steps (package-private so tests can call them directly) ─

    /**
     * Step 1: rename all camelCase keys to snake_case.
     * Keys already in snake_case pass through unchanged.
     *
     * Uses LinkedHashMap to preserve insertion order — important for
     * deterministic output in tests and logging.
     */
    Map<String, Object> convertCamelToSnake(Map<String, Object> payload) {
        var result = new LinkedHashMap<String, Object>();
        for (var entry : payload.entrySet()) {
            String snake = CAMEL_TO_SNAKE.matcher(entry.getKey())
                                         .replaceAll("$1_$2")
                                         .toLowerCase();
            result.put(snake, entry.getValue());
        }
        return result;
    }

    /**
     * Step 2: drop entries whose value is null, blank string, empty collection,
     * or empty map. Non-string non-null values (numbers, booleans) are kept.
     */
    Map<String, Object> removeNullsAndEmpty(Map<String, Object> payload) {
        var result = new LinkedHashMap<String, Object>();
        for (var entry : payload.entrySet()) {
            Object v = entry.getValue();
            if (v == null) continue;
            if (v instanceof String s && s.isBlank()) continue;
            if (v instanceof Collection<?> c && c.isEmpty()) continue;
            if (v instanceof Map<?, ?> m && m.isEmpty()) continue;
            result.put(entry.getKey(), v);
        }
        return result;
    }

    /**
     * Step 3: if a value is a String that parses cleanly as a Long or Double,
     * replace it with the numeric type. Non-numeric strings are left alone.
     *
     * Order matters: try Long first (exact integers), then Double (decimals).
     * This avoids turning "42" into 42.0 unnecessarily.
     */
    Map<String, Object> coerceNumericStrings(Map<String, Object> payload) {
        var result = new LinkedHashMap<String, Object>();
        for (var entry : payload.entrySet()) {
            Object v = entry.getValue();
            if (v instanceof String s) {
                try {
                    result.put(entry.getKey(), Long.parseLong(s));
                    continue;
                } catch (NumberFormatException ignored) {}
                try {
                    result.put(entry.getKey(), Double.parseDouble(s));
                    continue;
                } catch (NumberFormatException ignored) {}
            }
            result.put(entry.getKey(), v);
        }
        return result;
    }

    /**
     * Step 4: replace the value of any PII field with "[REDACTED]".
     * This runs AFTER camelCase conversion, so we only need to check
     * snake_case names (e.g. "credit_card" not "creditCard").
     */
    Map<String, Object> redactPiiFields(Map<String, Object> payload) {
        var result = new LinkedHashMap<String, Object>();
        for (var entry : payload.entrySet()) {
            if (PII_FIELDS.contains(entry.getKey().toLowerCase())) {
                result.put(entry.getKey(), "[REDACTED]");
            } else {
                result.put(entry.getKey(), entry.getValue());
            }
        }
        return result;
    }
}
